from pydantic import BaseModel, Field
from typing import List, Dict, Optional
from datetime import datetime


class Query(BaseModel):
    """
    Raw text input that will be converted to embeddings for similarity search
    """
    text: str = Field(..., description="The original query text provided by the user")
    normalized_text: Optional[str] = Field(None, description="The normalized version of the query text after preprocessing")
    embedding: Optional[List[float]] = Field(None, description="Vector representation of the text generated by Cohere model")
    filters: Optional[Dict] = Field(default_factory=dict, description="Optional metadata filters to apply during retrieval")

    class Config:
        # Allow embedding to be a list of floats
        arbitrary_types_allowed = True


class RetrievedChunk(BaseModel):
    """
    Content segment from the knowledge base with associated metadata
    """
    id: str = Field(..., description="Unique identifier for the chunk")
    content: str = Field(..., description="The actual text content of the chunk")
    score: float = Field(..., ge=0.0, le=1.0, description="Similarity score from the vector search")
    metadata: Dict = Field(..., description="Additional information including URL, title, and chunk index")
    embedding: Optional[List[float]] = Field(None, description="Vector representation of the chunk content")

    class Config:
        # Allow embedding to be a list of floats
        arbitrary_types_allowed = True


class ValidationResult(BaseModel):
    """
    Assessment of retrieval quality including relevance scores and ordering accuracy
    """
    query_text: str = Field(..., description="The original query text")
    retrieved_chunks: List[RetrievedChunk] = Field(default_factory=list, description="List of chunks returned by the search")
    relevance_score: float = Field(0.0, ge=0.0, le=1.0, description="Overall relevance score of the results")
    ordering_accuracy: float = Field(0.0, ge=0.0, le=1.0, description="Accuracy of the ordering by similarity")
    metadata_completeness: float = Field(0.0, ge=0.0, le=1.0, description="Percentage of chunks with complete metadata")
    execution_time: float = Field(0.0, ge=0.0, description="Time taken for the entire retrieval process")
    confidence_threshold_met: bool = Field(False, description="Whether results meet minimum confidence threshold")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the validation was performed")


class QdrantSearchResult(BaseModel):
    """
    Raw result from Qdrant search operation before validation
    """
    points: List[Dict] = Field(default_factory=list, description="List of points returned by Qdrant")
    query_vector: Optional[List[float]] = Field(None, description="The vector used for the search")
    search_params: Dict = Field(default_factory=dict, description="Parameters used for the search operation")
    collection_name: str = Field(..., description="Name of the collection searched")

    class Config:
        # Allow embedding to be a list of floats
        arbitrary_types_allowed = True