from pydantic import BaseModel, Field, validator
from typing import Optional, List
from datetime import datetime
from uuid import uuid4

class Query(BaseModel):
    """
    Represents a user query submitted to the system
    """
    id: str = Field(default_factory=lambda: str(uuid4()), description="Unique identifier for the query (UUID)")
    user_input: str = Field(..., description="Original user query text")
    query_embedding: Optional[List[float]] = Field(default=None, description="Vector embedding of the query (768 dimensions)")
    session_id: str = Field(..., description="Session identifier for conversation context")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the query was made")
    response_generated: Optional[str] = Field(default=None, description="The response generated by the system")
    retrieved_context_ids: List[str] = Field(default_factory=list, description="IDs of document chunks used in response")

    @validator('user_input')
    def validate_user_input(cls, v):
        """Validate that user input is not empty"""
        if not v.strip():
            raise ValueError('User input must not be empty')
        return v

    @validator('query_embedding')
    def validate_query_embedding(cls, v):
        """Validate that query embedding has exactly 768 dimensions"""
        if v is not None:
            from config.settings import settings
            if len(v) != settings.embedding_dimensions:
                raise ValueError(f'Query embedding must have exactly {settings.embedding_dimensions} dimensions')
        return v

    @validator('session_id')
    def validate_session_id(cls, v):
        """Validate that session ID follows standard format"""
        if not v.strip():
            raise ValueError('Session ID must not be empty')
        return v

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }

class QueryRequest(BaseModel):
    """
    Request model for submitting a query to the system
    """
    query: str = Field(..., description="The user's question or query")
    session_id: Optional[str] = Field(default_factory=lambda: str(uuid4()), description="Session identifier for maintaining conversation context")

    @validator('query')
    def validate_query(cls, v):
        """Validate that query is not empty"""
        if not v.strip():
            raise ValueError('Query cannot be empty')
        from config.settings import settings
        if len(v) > settings.max_query_length:
            raise ValueError(f'Query exceeds maximum length of {settings.max_query_length} characters')
        return v

class QueryResponse(BaseModel):
    """
    Response model for query results
    """
    query_id: str
    answer: str
    sources: List[dict]
    confidence: float

    @validator('confidence')
    def validate_confidence(cls, v):
        """Validate that confidence is between 0.0 and 1.0"""
        if not 0.0 <= v <= 1.0:
            raise ValueError('Confidence must be between 0.0 and 1.0')
        return v

class QueryResult(BaseModel):
    """
    Model for individual query results with sources
    """
    query_id: str
    answer: str
    sources: List[dict] = Field(default_factory=list)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)

    @validator('confidence')
    def validate_confidence(cls, v):
        """Validate that confidence is between 0.0 and 1.0"""
        if not 0.0 <= v <= 1.0:
            raise ValueError('Confidence must be between 0.0 and 1.0')
        return v