import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the course content
  courseSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['introduction'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 1: Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/index',
        'module-1-ros2/chapter-1',
        'module-1-ros2/chapter-2',
        'module-1-ros2/chapter-3',
        'module-1-ros2/chapter-4',
        'module-1-ros2/chapter-5',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: Simulation Environments',
      items: [
        'module-2-simulation/index',
        'module-2-simulation/chapter-6',
        'module-2-simulation/chapter-7',
        'module-2-simulation/chapter-8',
        'module-2-simulation/chapter-9',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Module 3: AI Integration with Isaac',
      items: [
        'module-3-isaac/index',
        'module-3-isaac/chapter-10',
        'module-3-isaac/chapter-11',
        'module-3-isaac/chapter-12',
        'module-3-isaac/chapter-13',
        'module-3-isaac/chapter-14',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Module 4: Voice-Controlled Robotics',
      items: [
        'module-4-vla/index',
        'module-4-vla/chapter-15',
        'module-4-vla/chapter-16',
        'module-4-vla/chapter-17',
        'module-4-vla/chapter-18',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Exercises',
      items: [
        'exercises/index',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api-reference/index',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Accessibility',
      items: [
        'accessibility',
        'screen-reader-guide',
        'keyboard-navigation',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Collaborative Learning',
      items: [
        'collaborative-learning',
        'peer-review-template',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        'capstone-integration-guide',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Validation Tools',
      items: [
        'automated-validation-tools',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Performance Optimization',
      items: [
        'performance-optimization',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Progress Tracking',
      items: [
        'progress-tracking-analytics',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Cloud & Backup Solutions',
      items: [
        'cloud-backup-alternatives',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Security & Privacy',
      items: [
        'security-privacy-llm',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Deployment Guides',
      items: [
        'deployment-institutional',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Peer Testing & Review',
      items: [
        'peer-testing-review',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Course Evaluation & Feedback',
      items: [
        'course-evaluation-feedback',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Automated Pipelines',
      items: [
        'automated-pipelines',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Instructor & TA Resources',
      items: [
        'instructor-ta-documentation',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Quality Assurance',
      items: [
        'quality-assurance-processes',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Capstone Showcase',
      items: [
        'capstone-showcase-templates',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Final Validation',
      items: [
        'final-course-validation',
      ],
      collapsed: true,
    },
  ],
};

export default sidebars;
